#!/usr/bin/env bash
# Emit project.vendor.generated.yml with optional proprietary framework
# links and JWBle-only FMDB sources. Regenerated on every bootstrap.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VENDOR="$ROOT/Vendor"
OUT="$ROOT/project.vendor.generated.yml"

app_deps=()
app_sources=()
test_deps=()

add_framework() {
  local name="$1"
  if [[ -d "$VENDOR/${name}.framework" ]]; then
    app_deps+=("      - framework: Vendor/${name}.framework
        embed: true
        codeSign: true")
    test_deps+=("      - framework: Vendor/${name}.framework
        embed: false
        codeSign: false")
  fi
}

add_framework JWBle
add_framework RTKAudioConnectSDK
add_framework RTKLEFoundation
add_framework RTKOTASDK

add_framework VeepooBleSDK
add_framework ABParTool
add_framework DFUnits
add_framework GRDFUSDK
add_framework JLDialUnit
add_framework JL_BLEKit
add_framework ZipZap

if [[ -d "$VENDOR/JWBle.framework" ]]; then
  app_sources+=("      - path: Vendor/FMDB/FMDatabaseAdditions.m")
  app_sources+=("      - path: Vendor/FMDB/FMDatabaseAdditions.h")
  app_deps+=("      - framework: Vendor/CocoaLumberjack.framework
        embed: true
        codeSign: true")
  test_deps+=("      - framework: Vendor/CocoaLumberjack.framework
        embed: false
        codeSign: false")
fi

{
  echo "# Auto-generated by scripts/generate-vendor-yml.sh — do not edit."
  echo "targets:"
  echo "  FeralCompanion:"
  if [[ ${#app_sources[@]} -gt 0 ]]; then
    echo "    sources:"
    printf '%s\n' "${app_sources[@]}"
  fi
  if [[ ${#app_deps[@]} -gt 0 ]]; then
    echo "    dependencies:"
    printf '%s\n' "${app_deps[@]}"
  fi
  echo "  FeralCompanionTests:"
  if [[ ${#test_deps[@]} -gt 0 ]]; then
    echo "    dependencies:"
    printf '%s\n' "${test_deps[@]}"
  fi
} > "$OUT"
