#!/usr/bin/env bash
# Emit project.vendor.generated.yml with optional proprietary framework
# links and JWBle-only FMDB sources. Regenerated on every bootstrap.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VENDOR="$ROOT/Vendor"
OUT="$ROOT/project.vendor.generated.yml"

app_deps=()
app_sources=()
test_deps=()

# Static frameworks (an `ar archive` Mach-O) must be LINKED, never embedded:
# Xcode's "Embed Frameworks" phase runs bitcode_strip, which only works on
# dynamic Mach-O dylibs and hard-fails on static archives. Detect the arm64
# device slice and set embed/codeSign accordingly.
add_framework() {
  local name="$1"
  local fw="$VENDOR/${name}.framework"
  [[ -d "$fw" ]] || return 0
  local bin="$fw/${name}"
  local embed="true" sign="true"
  if [[ -f "$bin" ]]; then
    local tmp="/tmp/.vendorcheck_${name}" desc
    if lipo "$bin" -thin arm64 -output "$tmp" >/dev/null 2>&1; then
      desc="$(file -b "$tmp")"
    else
      desc="$(file -b "$bin")"
    fi
    rm -f "$tmp" 2>/dev/null || true
    if [[ "$desc" == *"ar archive"* ]]; then
      embed="false"
      sign="false"
    fi
  fi
  app_deps+=("      - framework: Vendor/${name}.framework
        embed: ${embed}
        codeSign: ${sign}")
  test_deps+=("      - framework: Vendor/${name}.framework
        embed: false
        codeSign: false")
}

add_framework JWBle
add_framework RTKAudioConnectSDK
add_framework RTKLEFoundation
add_framework RTKOTASDK

add_framework VeepooBleSDK
add_framework ABParTool
add_framework DFUnits
add_framework GRDFUSDK
add_framework JLDialUnit
add_framework JL_BLEKit
add_framework ZipZap

if [[ -d "$VENDOR/JWBle.framework" ]]; then
  app_sources+=("      - path: Vendor/FMDB/FMDatabaseAdditions.m")
  app_sources+=("      - path: Vendor/FMDB/FMDatabaseAdditions.h")
  app_deps+=("      - framework: Vendor/CocoaLumberjack.framework
        embed: true
        codeSign: true")
  test_deps+=("      - framework: Vendor/CocoaLumberjack.framework
        embed: false
        codeSign: false")
fi

{
  echo "# Auto-generated by scripts/generate-vendor-yml.sh — do not edit."
  echo "targets:"
  echo "  FeralCompanion:"
  if [[ ${#app_sources[@]} -gt 0 ]]; then
    echo "    sources:"
    printf '%s\n' "${app_sources[@]}"
  fi
  if [[ ${#app_deps[@]} -gt 0 ]]; then
    echo "    dependencies:"
    printf '%s\n' "${app_deps[@]}"
  fi
  echo "  FeralCompanionTests:"
  if [[ ${#test_deps[@]} -gt 0 ]]; then
    echo "    dependencies:"
    printf '%s\n' "${test_deps[@]}"
  fi
} > "$OUT"
